### ISSUE TITLE
Brilliant Typora theme, but the bold function is invalid?

### ISSUE THREAD

**Issue by lippmann** [etigerstudio/typora-misty-theme#5] opened 2019-04-11 11:22 UTC
I love this theme so much and have been using it for a long time, but I found out recently that **the bold function** (ctrl + b for shortcut or `**text**` in markdown code) on Windows system is not working properly. I tried to reinstall the theme several times but without success. 

Maybe it's just my own problem but I hope you could check out whether it's a bug or something.

Again, thank you for providing us with such an elegant Typora theme.

**Comment by etigerstudio** [comment] 2019-04-11 17:18
Hi! It's my sheer pleasure that you enjoyed Misty Theme.

### The Issue
Unfortunately, I'm not able to reproduce your issue according to your feedback. I tested with keyboard shortcut, markdown code & right-click context menu in both mode, but it worked as expected.

If this issue still hasn't been resolved on your computer, it may be a Typora-specific issue or something needing further inspection. For example:
- Will bolding function work with other themes, such as default theme?
- Will it work when opening previously formatted markdown file?
- Will it work after Typora is updated or reinstalled to latest version?

Any screenshot related might also be helpful.

If you got any clue afterwards, feel free to post it here.

### My Test Platform
Typora Windows 0.9.68(latest), Misty Theme 0.5(latest), Windows 10 1703(2017 update).
### Screenshots
<img width="95" alt="Screen Shot 2019-04-11 at 11 40 17 PM" src="https://user-images.githubusercontent.com/2973222/55976906-22460080-5cc0-11e9-976e-7bfe96d86da7.png">
<img width="275" alt="Screen Shot 2019-04-11 at 11 39 29 PM" src="https://user-images.githubusercontent.com/2973222/55976915-2540f100-5cc0-11e9-914c-8f86066306d1.png">
<img width="122" alt="Screen Shot 2019-04-11 at 11 39 48 PM" src="https://user-images.githubusercontent.com/2973222/55976925-283be180-5cc0-11e9-96e0-692f514ad980.png">
<img width="99" alt="Screen Shot 2019-04-11 at 11 38 29 PM" src="https://user-images.githubusercontent.com/2973222/55976929-2a05a500-5cc0-11e9-94cd-87ed0e824522.png">
<img width="131" alt="Screen Shot 2019-04-11 at 11 38 55 PM" src="https://user-images.githubusercontent.com/2973222/55976937-2bcf6880-5cc0-11e9-8356-92978e5fc792.png">

**Comment by lippmann** [comment] 2019-04-12 06:11
Thank you for replying. It seems my problem. I've tweaked some codes with an user.css file, and there's no similar problem in other themes either, maybe it's the font I use or something. I'm gonna fix it myself. Cheers.

**Comment by etigerstudio** [comment] 2019-04-12 08:29
Closing this issue. Anyway, thank you for posting this issue to us here. You may have to look into your custom overrides. You could reopen one issue if you need any further assistance at any time.

**Closed as completed by etigerstudio** 2019-04-12 08:29 UTC
Labels: bug
